In [5]:
import pandas as pd

# Initial data
data1 = {'Make': ['ARCTIC CAT'], 'Model': ['all models'], 'Vendor Code': ['NACH'], 'Vendor Name': ['NACHMAN INTERNATIONAL CO.LTD'],
         'MPN': ['AT-01300'], 
         'AD Item Number': ['999733'], 
         'Vendor Notes': [pd.NA], 
         'REF#': [pd.NA], 
         'OEM#': ['3303-125']}

# List of models
new_list_models = [
'DVX 50'



 

]

oem_numbers = ['3303-125']

# Range of years
years = list(range(2006, 2009))

# Function to generate DataFrame for each model
def generate_df(model, data, year):
    data_copy = data.copy()  # Create a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    for oem in oem_numbers:
        data1['OEM#'] = oem
        df1 = pd.concat([generate_df(model, data1, year) for model in new_list_models], ignore_index=True)
        dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print the final DataFrame
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD Item Number,Vendor Notes,REF#,OEM#,Year
0,ARCTIC CAT,DVX 50,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2006
1,ARCTIC CAT,DVX 50,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2007
2,ARCTIC CAT,DVX 50,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2008

In [6]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\SECTION 01\Coils\MERGE\1.csv"
final_df.to_csv(file_path, index=False)

In [7]:
import pandas as pd

# Initial data
data1 = {'Make': ['ARCTIC CAT'], 'Model': ['all models'], 'Vendor Code': ['NACH'], 'Vendor Name': ['NACHMAN INTERNATIONAL CO.LTD'],
         'MPN': ['AT-01300'], 
         'AD Item Number': ['999733'], 
         'Vendor Notes': [pd.NA], 
         'REF#': [pd.NA], 
         'OEM#': ['3303-125']}

# List of models
new_list_models = [
'Alterra 90'



 

]

oem_numbers = ['3303-125']

# Range of years
years = list(range(2017, 2024))

# Function to generate DataFrame for each model
def generate_df(model, data, year):
    data_copy = data.copy()  # Create a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    for oem in oem_numbers:
        data1['OEM#'] = oem
        df1 = pd.concat([generate_df(model, data1, year) for model in new_list_models], ignore_index=True)
        dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print the final DataFrame
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD Item Number,Vendor Notes,REF#,OEM#,Year
0,ARCTIC CAT,Alterra 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2017
1,ARCTIC CAT,Alterra 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2018
2,ARCTIC CAT,Alterra 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2019
3,ARCTIC CAT,Alterra 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2020
4,ARCTIC CAT,Alterra 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2021
5,ARCTIC CAT,Alterra 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2022
6,ARCTIC CAT,Alterra 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2023

In [8]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\SECTION 01\Coils\MERGE\2.csv"
final_df.to_csv(file_path, index=False)

In [9]:
import pandas as pd

# Initial data
data1 = {'Make': ['ARCTIC CAT'], 'Model': ['all models'], 'Vendor Code': ['NACH'], 'Vendor Name': ['NACHMAN INTERNATIONAL CO.LTD'],
         'MPN': ['AT-01300'], 
         'AD Item Number': ['999733'], 
         'Vendor Notes': [pd.NA], 
         'REF#': [pd.NA], 
         'OEM#': ['3303-125']}

# List of models
new_list_models = [
'DVX 90 SE',
'DVX 90'




 

]

oem_numbers = ['3303-125']

# Range of years
years = list(range(2017, 2024))

# Function to generate DataFrame for each model
def generate_df(model, data, year):
    data_copy = data.copy()  # Create a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    for oem in oem_numbers:
        data1['OEM#'] = oem
        df1 = pd.concat([generate_df(model, data1, year) for model in new_list_models], ignore_index=True)
        dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print the final DataFrame
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD Item Number,Vendor Notes,REF#,OEM#,Year
0,ARCTIC CAT,DVX 90 SE,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2017
1,ARCTIC CAT,DVX 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2017
2,ARCTIC CAT,DVX 90 SE,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2018
3,ARCTIC CAT,DVX 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2018
4,ARCTIC CAT,DVX 90 SE,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2019
5,ARCTIC CAT,DVX 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2019
6,ARCTIC CAT,DVX 90 SE,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2020
7,ARCTIC CAT,DVX 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2020
8,ARCTIC CAT,DVX 90 SE,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2021
9,ARCTIC CAT,DVX 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2021
10,ARCTIC CAT,DVX 90 SE,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2022
11,ARCTIC CAT,DVX 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2022
12,ARCTIC CAT,DVX 90 SE,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2023
13,ARCTIC CAT,DVX 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,3303-125,2023

In [10]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\SECTION 01\Coils\MERGE\3.csv"
final_df.to_csv(file_path, index=False)

In [13]:
import pandas as pd

# Initial data
data1 = {'Make': ['YAMAHA'], 'Model': ['all models'], 'Vendor Code': ['NACH'], 'Vendor Name': ['NACHMAN INTERNATIONAL CO.LTD'],
         'MPN': ['AT-01300'], 
         'AD Item Number': ['999733'], 
         'Vendor Notes': [pd.NA], 
         'REF#': [pd.NA], 
         'OEM#': ['3303-125']}

# List of models
new_list_models = [
'YFM90 Raptor'



 

]

oem_numbers = ['BD3-H2320-00']

# Range of years
years = list(range(2016, 2024))

# Function to generate DataFrame for each model
def generate_df(model, data, year):
    data_copy = data.copy()  # Create a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    for oem in oem_numbers:
        data1['OEM#'] = oem
        df1 = pd.concat([generate_df(model, data1, year) for model in new_list_models], ignore_index=True)
        dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print the final DataFrame
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD Item Number,Vendor Notes,REF#,OEM#,Year
0,YAMAHA,YFM90 Raptor,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2016
1,YAMAHA,YFM90 Raptor,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2017
2,YAMAHA,YFM90 Raptor,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2018
3,YAMAHA,YFM90 Raptor,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2019
4,YAMAHA,YFM90 Raptor,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2020
5,YAMAHA,YFM90 Raptor,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2021
6,YAMAHA,YFM90 Raptor,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2022
7,YAMAHA,YFM90 Raptor,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2023

In [14]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\SECTION 01\Coils\MERGE\4.csv"
final_df.to_csv(file_path, index=False)

In [15]:
import pandas as pd

# Initial data
data1 = {'Make': ['YAMAHA'], 'Model': ['all models'], 'Vendor Code': ['NACH'], 'Vendor Name': ['NACHMAN INTERNATIONAL CO.LTD'],
         'MPN': ['AT-01300'], 
         'AD Item Number': ['999733'], 
         'Vendor Notes': [pd.NA], 
         'REF#': [pd.NA], 
         'OEM#': ['3303-125']}

# List of models
new_list_models = [
'YFM90 Grizzly 90'



 

]

oem_numbers = ['BD3-H2320-00']

# Range of years
years = list(range(2019, 2024))

# Function to generate DataFrame for each model
def generate_df(model, data, year):
    data_copy = data.copy()  # Create a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    for oem in oem_numbers:
        data1['OEM#'] = oem
        df1 = pd.concat([generate_df(model, data1, year) for model in new_list_models], ignore_index=True)
        dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print the final DataFrame
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD Item Number,Vendor Notes,REF#,OEM#,Year
0,YAMAHA,YFM90 Grizzly 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2019
1,YAMAHA,YFM90 Grizzly 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2020
2,YAMAHA,YFM90 Grizzly 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2021
3,YAMAHA,YFM90 Grizzly 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2022
4,YAMAHA,YFM90 Grizzly 90,NACH,NACHMAN INTERNATIONAL CO.LTD,AT-01300,999733,<NA>,<NA>,BD3-H2320-00,2023

In [16]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\SECTION 01\Coils\MERGE\5.csv"
final_df.to_csv(file_path, index=False)